# Generated by Django 4.2.23 on 2025-08-31 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('monthly_dues', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('annual_dues', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(help_text='Unique member ID number', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('work_phone', models.CharField(blank=True, max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('fax_number', models.CharField(blank=True, max_length=20)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('home_address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('work_title', models.CharField(blank=True, max_length=100)),
                ('work_address', models.CharField(blank=True, max_length=200)),
                ('work_city', models.CharField(blank=True, max_length=100)),
                ('work_state', models.CharField(blank=True, max_length=50)),
                ('work_zip_code', models.CharField(blank=True, max_length=20)),
                ('work_country', models.CharField(blank=True, max_length=100)),
                ('date_joined', models.DateField(help_text='Date member joined the club')),
                ('expires', models.DateField(blank=True, help_text='Membership expiration date', null=True)),
                ('milestone', models.DateField(blank=True, help_text='Important milestone date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deceased', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the member')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_type', models.ForeignKey(help_text='Type of membership', on_delete=django.db.models.deletion.PROTECT, to='members.membertype')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, help_text='Relationship to member (spouse, friend, sponsor, etc.)', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='members.member')),
            ],
            options={
                'ordering': ['friend_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_date', models.DateField(help_text='Date payment was received')),
                ('period_start', models.DateField(blank=True, help_text='Start date of the period this payment covers', null=True)),
                ('period_end', models.DateField(blank=True, help_text='End date of the period this payment covers', null=True)),
                ('check_number', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.paymentmethod')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['member', 'payment_date'], name='members_pay_member__803697_idx'), models.Index(fields=['payment_date'], name='members_pay_payment_1f266b_idx'), models.Index(fields=['amount'], name='members_pay_amount_0b78f3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_id'], name='members_mem_member__1c9876_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='members_mem_last_na_92a910_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_type'], name='members_mem_member__d4344f_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_active'], name='members_mem_is_acti_65d5c9_idx'),
        ),
    ]
