# Generated by Django 4.2.23 on 2025-09-06 20:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(max_length=50, unique=True)),
                ('member_dues', models.DecimalField(decimal_places=2, max_digits=8)),
                ('num_months', models.IntegerField()),
            ],
            options={
                'db_table': 'members_membertype',
                'ordering': ['member_type'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'members_paymentmethod',
                'ordering': ['payment_method'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('member_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('preferred_member_id', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('expiration_date', models.DateField()),
                ('milestone_date', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField()),
                ('date_inactivated', models.DateField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True)),
                ('home_city', models.CharField(blank=True, max_length=100)),
                ('home_state', models.CharField(blank=True, max_length=2)),
                ('home_zip', models.CharField(blank=True, max_length=10)),
                ('home_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.membertype')),
            ],
            options={
                'db_table': 'members_member',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.member')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.paymentmethod')),
            ],
            options={
                'db_table': 'members_payment',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['member', 'date'], name='members_pay_member__bc6bb3_idx'), models.Index(fields=['date'], name='members_pay_date_58dfc2_idx'), models.Index(fields=['amount'], name='members_pay_amount_0b78f3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_id'], name='members_mem_member__1c9876_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='members_mem_last_na_92a910_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='members_mem_status_734de0_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['expiration_date'], name='members_mem_expirat_e91d68_idx'),
        ),
    ]
